# This RBAC file should be applied if custom-tekton-listener is deployed in the same namespace
# where the tekton pipelines live

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: custom-tekton-listener
  namespace: tekton-pipelines
rules:
- apiGroups: [""]
  resources: 
    - "configmaps"
    - "secrets"
  verbs: ["get", "list"]
- apiGroups: ["tekton.dev"]
  resources: 
    - "pipelineruns"
  verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: custom-tekton-listener
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: custom-tekton-listener
  namespace: tekton-pipelines
roleRef:
  kind: Role 
  name: custom-tekton-listener
  apiGroup: rbac.authorization.k8s.io
