apiVersion: v1
kind: ConfigMap
metadata:
  name: ws-persistent-volume-claim
  namespace: custom-tekton-listener
data:
  template: |
    - name: source-pvc
      persistentVolumeClaim:
        claimName: mypvc
      subPath: my-subdir